#!/bin/bash
# postinst script for se3-ocs
#
# see: dh_installdeb(1)

set -e


case "$1" in
    install|configure)

### on suppose que l'on est sous debian :D  ####
WWWPATH="/var/www"
## recuperation des variables necessaires pour interoger mysql ###
if [ -e $WWWPATH/se3/includes/config.inc.php ]; then
	dbhost=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbhost=" | cut -d = -f2 | cut -d \" -f2`
	dbname=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbname=" | cut	-d = -f 2 |cut -d \" -f 2`
	dbuser=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbuser=" | cut -d = -f 2 | cut -d \" -f 2`
	dbpass=`cat $WWWPATH/se3/includes/config.inc.php | grep "dbpass=" | cut -d = -f 2 | cut -d \" -f 2`
else
	echo "Fichier de configuration inaccessible, le script ne peut se poursuivre."
	exit 1
fi

test_exist=`echo "SELECT id FROM params WHERE name='inventaire'" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N`
if [ "X$test_exist" = "X" ]; then # if empty
	echo "INSERT INTO params VALUES ('', 'inventaire', '0', 0, 'Activation de l\'inventaire', 6)" | mysql -h $dbhost $dbname -u $dbuser -p$dbpass -N
fi
	
cachedir="/var/cache/se3_install/ocs"
if [ -e "$cachedir/old_version" ]; then
	if [ -n "$(grep "^2.0" $cachedir/old_version)" ]; then
		echo "mise à jour du paquet uniquement"
		exit 0
	fi
fi
# Creation du MDP_OCS ou maj
MDP_OCS=`date|md5sum|cut -c 3-9`

### recup pass root mysql
if [ ! -e /root/.my.cnf ]; then
echo "Lecture du pass root mysql impossible, /root/.my.cnf inexistant" 
exit 1
fi

PASS_SQL="$(grep -vE '^[[:space:]]*#' /root/.my.cnf | grep password /root/.my.cnf | cut -d "=" -f2)" 
# On teste si la base existe deja et si on a le mot de passe
if [ -e $WWWPATH/se3/includes/dbconfig.inc.php ]; then
	MAJ_OCS=1
	# On supprime l'ancienne version si elle existe
	if [ -e /etc/apache2se/conf.d/ocsinventory.conf ]; then
		/var/cache/se3_install/ocs/clean-oldocs.sh
		# nouvelle installation
		mysql -u root -p"$PASS_SQL" < /var/cache/se3_install/ocs/ocsbase.sql 

	fi	
else
	# nouvelle installation
	mysql -u root -p"$PASS_SQL" < /var/cache/se3_install/ocs/ocsbase.sql 2>/dev/null
fi

# mysql -h localhost -u root -p$password --force < /var/cache/se3_install/ocsbase-se3.sql 2>/dev/null

#mysql -u root -p"$PASS_SQL" -e "GRANT ALL PRIVILEGES ON ocsweb.* TO 'ocs'@'%' IDENTIFIED BY '$MDP_OCS';"
mysql -u root -p"$PASS_SQL" -e "GRANT ALL PRIVILEGES ON ocsweb.* TO 'ocs'@'localhost' IDENTIFIED BY '$MDP_OCS';"
mysql -u root -p"$PASS_SQL" -e "FLUSH PRIVILEGES;"

# Creation de la conf
echo "<?php
\$_SESSION[\"SERVEUR_SQL\"]=\"localhost\";
\$_SESSION[\"COMPTE_BASE\"]=\"ocs\";
\$_SESSION[\"PSWD_BASE\"]=\"$MDP_OCS\";
?>" > /var/www/se3/includes/dbconfig.inc.php

cd /opt/install/ocs/
./setup-ocs-se3.sh $MDP_OCS

# Nettoyage ancienne commande
template_base="/home/templates/base/logon.bat"
if [ -e "$template_base" ]; then
	sed -i "/ocs.bat/d" $template_base
	sed -i "/cpauOcs.job/d" $template_base
fi

if [ -e "/var/se3/Progs/ro/deploy" ]; then
	rm -rf "/var/se3/Progs/ro/deploy"
fi

# installation du xml 
OCSCLIENTURL="http://svn.tice.ac-caen.fr/svn/SambaEdu3/wpkg-packages-ng/files/ocs"
OCSCLIENTLOCAL="/var/se3/unattended/install/wpkg/tmp/ocs-client.xml"
if [ -e "$OCSCLIENTLOCAL" ]; then
	rm -f $OCSCLIENTLOCAL
fi

wget $OCSCLIENTURL/ocs-client.xml? -O $OCSCLIENTLOCAL

/var/www/se3/wpkg/bin/installPackage.sh $OCSCLIENTLOCAL 0 admin 0 1

/var/www/se3/wpkg/bin/associer.sh Associer ocs-client _TousLesPostes admin || true

# perl -pi -e "s/.*OCS_DB_PWD.*/PerlSetVar OCS_DB_PWD $MDP_OCS/" /etc/ocsinventory/ocsinventory.conf

/usr/share/se3/scripts/permse3

# Reloadind apache2se
/etc/init.d/apache2se reload 

	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac 

exit 0

